language: node_js
node_js:
  - "10"
  - "8"
  - "6"
before_install:
  - npm install npm@latest -g
install:
  - npx install-peerdeps --dev eslint-config
  - npm install && lerna bootstrap --concurrency=1
script:
  - npm run test-all
